### PR TITLE
devices: Sanders for Official Device

### PR DESCRIPTION
**Pull request by marshmello61**

### CODE REVIEW

**Comment by peaktogoo** [comment]
Let check it first before merge

**Comment by marshmello61** [comment]
I know what you are saying the above and below lines. But it appears the same after merged

**Comment by peaktogoo** [comment]
You have to make a new file called codename.json
codename is like whyred

marshmello61 , and may i know who you are?

**Comment by peaktogoo** [comment]
User is not ready at this time, The pull request is not ready also.

You can always make a new pull request with proper format.

**Pull request closed without merging**
